// Generated by https://quicktype.io

export interface ResUser {
  _id: string;
  first_name: string;
  last_name: string;
  // age: number;
  avatar: string;
  email: string;
  status: string;
  role: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
  friends: string[];
  friend_requests: string[];
  sent_friend_requests: string[];
  otp: string;
  otp_expired: string;
  fcmToken: string[];
}
// Generated by https://quicktype.io

export interface ResLogin {
  success: boolean;
  token: string;
}
// Generated by https://quicktype.io

export interface ResFriendList {
  success: boolean;
  users: Friend[];
  total: number;
}

export interface Friend {
  _id: string;
  first_name: string;
  last_name: string;
  avatar: string;
  email: string;
}
export type ResRegister = {
  success: boolean;
  messaage: string;
};
