// Generated by https://quicktype.io

import {Resp_User} from './auth.type';

export interface ChatProps {
  _id: string;
  members: string[];
  createdAt: string;
  updatedAt: string;
  lastMessage?: string;
  name: string;
}

export interface Member {
  _id: string;
  first_name: string;
  last_name: string;
  avatar: string;
}
// Generated by https://quicktype.io

export interface LastMessage {
  _id: string;
  chatId: string;
  senderId: string;
  files: string[];
  text: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
}
// Generated by https://quicktype.io

export interface Message {
  id: string;
  user: Resp_User;
  text: string;
  attachments: string[];
  reactions: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Sender {
  _id: string;
  first_name: string;
  last_name: string;
  avatar: null;
}
// Generated by https://quicktype.io

export interface ResSendMessage {
  chatId: string;
  senderId: string;
  text: string;
  files: string[];
  _id: string;
  createdAt: string;
  updatedAt: string;
  __v: number;
  id: string;
}

export interface Channel {
  id: string;
  type: string;
  name: string;
  last_message: string;
  members: string[];
  createdAt: string;
  updatedAt: string;
}
