// Generated by https://quicktype.io

export interface Comment {
  _id: string;
  author: Author;
  text: string;
  files: string[];
  postId: string;
  comments: Comment[];
  users_liked: any[];
  isSmall: boolean;
  createdAt: string;
  updatedAt: string;
  __v: number;
}

export interface Author {
  _id: string;
  first_name: string;
  last_name: string;
  avatar: null;
}
