// Generated by https://quicktype.io

export interface Comment {
  id: string;
  author: string;
  text: string;
  files: string[];
  postId: string;
  commentId?: string;
  users_liked: string[];
  createdAt: string;
  updatedAt: string;
}

export interface Reply {
  id: string;
  author: string;
  text: string;
  files: string[];
  commentId: string;
  postId: string;
  users_liked: string[];
  createdAt: string;
  updatedAt: string;
}
