// Generated by https://quicktype.io

export interface Comment {
  id: string;
  author: string;
  text: string;
  files: string[];
  postId: string;
  comments: Comment[];
  users_liked: string[];
  createdAt: string;
  updatedAt: string;
}
