// Generated by https://quicktype.io

import {Friend} from './auth.type';

export interface Post {
  _id: string;
  author: Omit<Friend, 'email'>;
  description: string;
  files: string[];
  users_receive: string[];
  users_liked: any[];
  total_comments: number;
  createdAt: string;
  updatedAt: string;
  __v: number;
}
